### ISSUE TITLE
Fatal Exception: java.io.FileNotFoundException on registerDeviceToken

### ISSUE THREAD

**Issue by AbdulDroid** [customerio/customerio-android#155] opened 2023-01-03 22:39 UTC
**SDK version:** v3.1.0

**Environment:** Production

**Are logs available?** 
```
Fatal Exception: java.io.FileNotFoundException: /data/user/0/ng.com.fairmoney.fairmoney/files/io.customer/24485baaaacb896e63da/queue/tasks/1152fc26-8470-4294-9100-138b237eed53.json: open failed: ENOENT (No such file or directory)
       at libcore.io.IoBridge.open(IoBridge.java:574)
       at java.io.FileInputStream.<init>(FileInputStream.java:160)
       at kotlin.io.FilesKt__FileReadWriteKt.readText$default(FileReadWrite.kt:125)
       at kotlin.io.FilesKt__FileReadWriteKt.readText$default(FileReadWrite.kt:125)
       at io.customer.sdk.data.store.FileStorage.get(FileStorage.kt:62)
       at io.customer.sdk.queue.QueueStorageImpl.get(QueueStorage.kt:103)
       at io.customer.sdk.queue.QueueRunRequestImpl.runTasks(QueueRunRequest.kt:37)
       at io.customer.sdk.queue.QueueRunRequestImpl.runTasks$default(QueueRunRequest.kt:26)
       at io.customer.sdk.queue.QueueRunRequestImpl.run(QueueRunRequest.kt:23)
       at io.customer.sdk.queue.QueueImpl.run(Queue.kt:114)
       at io.customer.sdk.queue.QueueImpl$runAsync$1.invokeSuspend(Queue.kt:124)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
       at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by android.system.ErrnoException: open failed: ENOENT (No such file or directory)
       at libcore.io.Linux.open(Linux.java)
       at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
       at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
       at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
       at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8523)
       at libcore.io.IoBridge.open(IoBridge.java:560)
       at java.io.FileInputStream.<init>(FileInputStream.java:160)
       at kotlin.io.FilesKt__FileReadWriteKt.readText$default(FileReadWrite.kt:125)
       at kotlin.io.FilesKt__FileReadWriteKt.readText$default(FileReadWrite.kt:125)
       at io.customer.sdk.data.store.FileStorage.get(FileStorage.kt:62)
       at io.customer.sdk.queue.QueueStorageImpl.get(QueueStorage.kt:103)
       at io.customer.sdk.queue.QueueRunRequestImpl.runTasks(QueueRunRequest.kt:37)
       at io.customer.sdk.queue.QueueRunRequestImpl.runTasks$default(QueueRunRequest.kt:26)
       at io.customer.sdk.queue.QueueRunRequestImpl.run(QueueRunRequest.kt:23)
       at io.customer.sdk.queue.QueueImpl.run(Queue.kt:114)
       at io.customer.sdk.queue.QueueImpl$runAsync$1.invokeSuspend(Queue.kt:124)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
       at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Describe the bug**
This randomly happens and is currently affecting a lot of our users across several device brands

**To Reproduce**

**Expected behavior**
Device token is registered successfully without crashes

**Screenshots**

**Additional context**

**Comment by Shahroz16** [comment] 2023-01-04 03:23
Hey @AbdulDroid, thanks for reaching out. This is very strange and shouldn't be happening. 

Tasks/events such as "registering token" are saved on files before being sent to the server, and the exception looks like those files are deleted from the device. 

Can you find any pattern? is it a specific API level, or scienerio that might be causing it? 

or if you have any steps to reproduce?

**Comment by AbdulDroid** [comment] 2023-01-04 06:49
Hey @Shahroz16 
> Can you find any pattern? is it a specific API level, or scienerio that might be causing it?

I currently can't make any pattern from the errors it happens from API level 22 to API level 33

> or if you have any steps to reproduce? 

I currently can't find steps to reproduce it on any of my devices

**Comment by Shahroz16** [comment] 2023-01-04 11:35
Okay, we will keep an eye on this one, but do you think there might be any reason those users of yours would delete files? Or is there any functionality of your app that deletes files or let's users too?

Also, is the crash log always like this? I,e _file not found_ ?

Thank you for the help.

**Comment by AbdulDroid** [comment] 2023-01-04 11:39
> but do you think there might be any reason those users of yours would delete files?

None that I can think of.

> Or is there any functionality of your app that deletes files or let's users too?

None

> Also, is the crash log always like this? I,e file not found ?

Yes exactly the same, File not found at some location on the user's device

**Comment by Shahroz16** [comment] 2023-01-06 02:39
@AbdulDroid since we can't replicate it or find a cause of why that might be happening, we will just suppress the crash in this case, in next release.

**Comment by AbdulDroid** [comment] 2023-01-09 09:03
@Shahroz16 how does this affect the intended action before the crash? does the user device token still get persisted fine? how does this affect the functionality of the SDK generally on the affected user's device?

**Comment by Shahroz16** [comment] 2023-01-09 17:49
@AbdulDroid Ideally it shouldn't because we fetch the device token every time we get the opportunity and send it. So even if it didn't send the event the first time, it should in another attempt.

**Comment by AbdulDroid** [comment] 2023-01-23 08:16
@Shahroz16 please is there any update on this?

**Comment by Shahroz16** [comment] 2023-01-25 03:30
@AbdulDroid apologies as we couldn't get to this, we have not been able to reproduce it, we even check and there are measures in place for the times when files aren't available. 

If you could help us with any steps to reproduce it, that will be a big help.

**Comment by AbdulDroid** [comment] 2023-02-22 15:50
@Shahroz16 do we have a release that addresses this issue now? Is it safe to assume that with the merge of this proposed solution there's or there'll be a version that solves this issue?

**Comment by Shahroz16** [comment] 2023-02-22 15:54
@AbdulDroid thank you for checking on this, we have added some improvements but we have been unable to replicate it even once, and there are no other bug reports for this, so I am very hesitant to say this will fix everything on your end cause we aren't even sure what's causing it in the first place. 

So I would recommend, maybe installing a newer version and trying it.

**Comment by Shahroz16** [comment] 2023-03-07 10:51
@AbdulDroid we sent out a [fix](https://github.com/customerio/customerio-android/releases/tag/3.3.1) for this issue. 

Closing this ticket, please let us if the issue still persists after installing this version. Thank you for your patience.

**Closed by Shahroz16** 2023-03-07 10:51 UTC
Labels: bug, android
