### ISSUE TITLE
Some of the device ID is not registering a profile on UAT environment.

### ISSUE THREAD

**Issue by Sanjeev193016** [customerio/customerio-android#226] opened 2023-06-23 07:34 UTC
**SDK version:** **3.5.2**

**Are logs available?** 
[CIO]: identify profile d7061a7254bbf5e8
D/[CIO]: identify profile d7061a7254bbf5e8, {reason=-, device_model=HD1901, app_version=20.2.0, cio_sdk_version=30, timezone=Asia/Kolkata, created_at=1687502615, device_region=in, language=en, device_os=Android, unsubscribed=false, subscribe_source=Mobile_App, push_enabled=true, id=d7061a7254bbf5e8, email=}
I/[CIO]: adding queue task IdentifyProfile
D/[CIO]: added queue task data {"identifier":"d7061a7254bbf5e8","attributes":{"reason":"-","device_model":"HD1901","app_version":"20.2.0","cio_sdk_version":30,"timezone":"Asia/Kolkata","created_at":1687502615,"device_region":"in","language":"en","device_os":"Android","unsubscribed":"false","subscribe_source":"Mobile_App","push_enabled":"true","id":"d7061a7254bbf5e8","email":""}}
D/[CIO]: processing queue status QueueStatus(siteId=06f9c82b54a139b44d51, numTasksInQueue=1)
I/[CIO]: queue timer: scheduled to run queue in 30.0 seconds seconds
D/[CIO]: storing identifier on device storage d7061a7254bbf5e8
D/[CIO]: first time identified or changing identified profile
D/[CIO]: automatically registering device token to newly identified profile
I/[CIO]: registering device token fSX-oAfVT46HdIRA1CnsiC:APA91bHunTrg0iJi47nRCs8am3eAs_L3UBkEcaqWcHWkp2FqJRvy_Dm_bcq0PMrb0EoaB1i4xCjkvd61IWvsVtomMPU8e_YYwQPSGitsSzjGZhdt4uiS52l3e2ZKMVfTrneNcRcGTlI8, attributes: {device_os=30, device_model=HD1901, device_manufacturer=OnePlus, app_version=3.3.46, cio_sdk_version=3.5.1, device_locale=en-IN, push_enabled=true}
D/[CIO]: storing device token to device storage fSX-oAfVT46HdIRA1CnsiC:APA91bHunTrg0iJi47nRCs8am3eAs_L3UBkEcaqWcHWkp2FqJRvy_Dm_bcq0PMrb0EoaB1i4xCjkvd61IWvsVtomMPU8e_YYwQPSGitsSzjGZhdt4uiS52l3e2ZKMVfTrneNcRcGTlI8
I/[CIO]: adding queue task RegisterDeviceToken
D/[CIO]: added queue task data {"profileIdentified":"d7061a7254bbf5e8","device":{"id":"fSX-oAfVT46HdIRA1CnsiC:APA91bHunTrg0iJi47nRCs8am3eAs_L3UBkEcaqWcHWkp2FqJRvy_Dm_bcq0PMrb0EoaB1i4xCjkvd61IWvsVtomMPU8e_YYwQPSGitsSzjGZhdt4uiS52l3e2ZKMVfTrneNcRcGTlI8","platform":"android","lastUsed":1687502615,"attributes":{"device_os":30,"device_model":"HD1901","device_manufacturer":"OnePlus","app_version":"3.3.46","cio_sdk_version":"3.5.1","device_locale":"en-IN","push_enabled":true}}}
D/[CIO]: processing queue status QueueStatus(siteId=06f9c82b54a139b44d51, numTasksInQueue=2)
I/[CIO]: queue timer: scheduled to run queue in 30.0 seconds seconds
I/[CIO]: registering device token fSX-oAfVT46HdIRA1CnsiC:APA91bHunTrg0iJi47nRCs8am3eAs_L3UBkEcaqWcHWkp2FqJRvy_Dm_bcq0PMrb0EoaB1i4xCjkvd61IWvsVtomMPU8e_YYwQPSGitsSzjGZhdt4uiS52l3e2ZKMVfTrneNcRcGTlI8, attributes: {device_os=30, device_model=HD1901, device_manufacturer=OnePlus, app_version=3.3.46, cio_sdk_version=3.5.1, device_locale=en-IN, push_enabled=true}
D/[CIO]: storing device token to device storage fSX-oAfVT46HdIRA1CnsiC:APA91bHunTrg0iJi47nRCs8am3eAs_L3UBkEcaqWcHWkp2FqJRvy_Dm_bcq0PMrb0EoaB1i4xCjkvd61IWvsVtomMPU8e_YYwQPSGitsSzjGZhdt4uiS52l3e2ZKMVfTrneNcRcGTlI8
I/[CIO]: adding queue task RegisterDeviceToken
D/[CIO]: added queue task data {"profileIdentified":"d7061a7254bbf5e8","device":{"id":"fSX-oAfVT46HdIRA1CnsiC:APA91bHunTrg0iJi47nRCs8am3eAs_L3UBkEcaqWcHWkp2FqJRvy_Dm_bcq0PMrb0EoaB1i4xCjkvd61IWvsVtomMPU8e_YYwQPSGitsSzjGZhdt4uiS52l3e2ZKMVfTrneNcRcGTlI8","platform":"android","lastUsed":1687502615,"attributes":{"device_os":30,"device_model":"HD1901","device_manufacturer":"OnePlus","app_version":"3.3.46","cio_sdk_version":"3.5.1","device_locale":"en-IN","push_enabled":true}}}
D/[CIO]: processing queue status QueueStatus(siteId=06f9c82b54a139b44d51, numTasksInQueue=3)
I/[CIO]: queue timer: scheduled to run queue in 30.0 seconds seconds
D/[CIO]: Timer czvaaoihae making a timer for 30.0 seconds
D/[CIO]: Timer czvaaoihae making a timer for 30.0 seconds
I/System.out: 2131296975permission was granted
V/FA: Activity resumed, time: 268653351
D/DecorView: onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@7711e71[NewHomeActivity]
D/ViewRootImpl[NewHomeActivity]: windowFocusChanged hasFocus=true inTouchMode=true
V/FA: Inactivity, disconnecting from the service
D/[CIO]: Timer czvaaoihae timer is done! It's been reset
I/[CIO]: queue timer: now running queue
D/[CIO]: Timer czvaaoihae timer is being cancelled
D/[CIO]: queue starting to run tasks...
D/[CIO]: queue querying next task. criteria: QueueQueryCriteria(excludeGroups=[])
D/[CIO]: queue tasks left to run: 3 out of 3
D/[CIO]: queue next task to run: 8ee6b040-1db1-49f2-8175-3383905e8e4d, IdentifyProfile, {"identifier":"d7061a7254bbf5e8","attributes":{"reason":"-","device_model":"HD1901","app_version":"20.2.0","cio_sdk_version":30,"timezone":"Asia/Kolkata","created_at":1687502615,"device_region":"in","language":"en","device_os":"Android","unsubscribed":"false","subscribe_source":"Mobile_App","push_enabled":"true","id":"d7061a7254bbf5e8","email":""}}, QueueTaskRunResults(totalRuns=0)
D/[CIO]: queue task 8ee6b040-1db1-49f2-8175-3383905e8e4d ran successfully
D/[CIO]: queue deleting task 8ee6b040-1db1-49f2-8175-3383905e8e4d
D/[CIO]: queue querying next task. criteria: QueueQueryCriteria(excludeGroups=[])
D/[CIO]: queue tasks left to run: 2 out of 3
D/[CIO]: queue next task to run: 4f3b4f3c-b0c3-40b3-8907-4f229427e1a8, RegisterDeviceToken, {"profileIdentified":"d7061a7254bbf5e8","device":{"id":"fSX-oAfVT46HdIRA1CnsiC:APA91bHunTrg0iJi47nRCs8am3eAs_L3UBkEcaqWcHWkp2FqJRvy_Dm_bcq0PMrb0EoaB1i4xCjkvd61IWvsVtomMPU8e_YYwQPSGitsSzjGZhdt4uiS52l3e2ZKMVfTrneNcRcGTlI8","platform":"android","lastUsed":1687502615,"attributes":{"device_os":30,"device_model":"HD1901","device_manufacturer":"OnePlus","app_version":"3.3.46","cio_sdk_version":"3.5.1","device_locale":"en-IN","push_enabled":true}}}, QueueTaskRunResults(totalRuns=0)
D/[CIO]: queue task 4f3b4f3c-b0c3-40b3-8907-4f229427e1a8 ran successfully
D/[CIO]: queue deleting task 4f3b4f3c-b0c3-40b3-8907-4f229427e1a8
D/[CIO]: queue querying next task. criteria: QueueQueryCriteria(excludeGroups=[])
D/[CIO]: queue tasks left to run: 1 out of 3
D/[CIO]: queue next task to run: ed7a4097-beec-4a19-8f22-a299c9030e68, RegisterDeviceToken, {"profileIdentified":"d7061a7254bbf5e8","device":{"id":"fSX-oAfVT46HdIRA1CnsiC:APA91bHunTrg0iJi47nRCs8am3eAs_L3UBkEcaqWcHWkp2FqJRvy_Dm_bcq0PMrb0EoaB1i4xCjkvd61IWvsVtomMPU8e_YYwQPSGitsSzjGZhdt4uiS52l3e2ZKMVfTrneNcRcGTlI8","platform":"android","lastUsed":1687502615,"attributes":{"device_os":30,"device_model":"HD1901","device_manufacturer":"OnePlus","app_version":"3.3.46","cio_sdk_version":"3.5.1","device_locale":"en-IN","push_enabled":true}}}, QueueTaskRunResults(totalRuns=0)
D/[CIO]: queue task ed7a4097-beec-4a19-8f22-a299c9030e68 ran successfully
D/[CIO]: queue deleting task ed7a4097-beec-4a19-8f22-a299c9030e68
D/[CIO]: queue done running tasks
D/[CIO]: resetting queue tasks query criteria

**Describe the issue**
Some of the device id is not creating the profile on UAT environment but the same device id is working fine on Production environment. 

**Screenshots**

**Additional context**

**Comment by mrehan27** [comment] 2023-06-23 09:03
Hi @Sanjeev193016,

Thank you for reaching out to us and providing the details. I have reviewed the logs you shared, and everything seems to be in order. However, I would appreciate it if you could clarify a few points:

- Regarding the UAT environment, could you please provide more information about its setup? Do you have a separate workspace specifically designated for UAT, distinct from your Production environment?
- If you do have separate environments, it would be helpful to confirm whether you have correctly added the `siteId` and `apiKey` for both the UAT and Production environments.
- Additionally, please ensure that you are calling the `identify` method at the appropriate location within your application. Keep in mind that a profile will only be created once the `identify` method is invoked.
- Lastly, please verify that you are not mixing the application data between the UAT and Production environments. It's important to note that if you identify a profile within one workspace and later switch to a different workspace, the expected results may not be visible due to the behavior described above.

I hope these clarifications will help us pinpoint the issue more accurately. Please let us know if you have any further information or if there's anything else we can assist you with.

**Comment by byronmil** [comment] 2023-06-23 19:55
@Sanjeev193016 I was able to determine that the id `d7061a7254bbf5e8` was suppressed for the UAT workspace at one time, so it can not be reused unless it is unsuppressed (https://customer.io/docs/api/track/?region=eu#operation/unsuppress).

I'll write up a feature request to see if we can add errors to the log output when a suppressed identifier is identified, or otherwise provide you with that information so that you know what is causing the issue.

**Comment by Sanjeev193016** [comment] 2023-06-26 06:51
> @Sanjeev193016 I was able to determine that the id `d7061a7254bbf5e8` was suppressed for the UAT workspace at one time, so it can not be reused unless it is unsuppressed (https://customer.io/docs/api/track/?region=eu#operation/unsuppress).
> 
> I'll write up a feature request to see if we can add errors to the log output when a suppressed identifier is identified, or otherwise provide you with that information so that you know what is causing the issue.

Thank you so much for your prompt support. after unsuppressed this `d7061a7254bbf5e8` device id it's working fine and able to register user profile on UAT.

But please provide some logs when a suppressed identifier is identified so we can manage the user easily.

**Comment by Sanjeev193016** [comment] 2023-06-26 07:00
> Hi @Sanjeev193016,
> 
> Thank you for reaching out to us and providing the details. I have reviewed the logs you shared, and everything seems to be in order. However, I would appreciate it if you could clarify a few points:
> 
> * Regarding the UAT environment, could you please provide more information about its setup? Do you have a separate workspace specifically designated for UAT, distinct from your Production environment?
> * If you do have separate environments, it would be helpful to confirm whether you have correctly added the `siteId` and `apiKey` for both the UAT and Production environments.
> * Additionally, please ensure that you are calling the `identify` method at the appropriate location within your application. Keep in mind that a profile will only be created once the `identify` method is invoked.
> * Lastly, please verify that you are not mixing the application data between the UAT and Production environments. It's important to note that if you identify a profile within one workspace and later switch to a different workspace, the expected results may not be visible due to the behavior described above.
> 
> I hope these clarifications will help us pinpoint the issue more accurately. Please let us know if you have any further information or if there's anything else we can assist you with.

Hello @mrehan27,

Here you mentioned in last point that we should not mixing the data between the UAT and Production. then here the question is how we can test both environment UAT and Production in one device? 

Can you suggest the possible way to testing both environment?

**Comment by mrehan27** [comment] 2023-06-26 12:29
@Sanjeev193016 I apologize for any confusion caused earlier. To test both environments, you can use the same device if your apps have different app identifiers (`applicationId`) and can be installed in parallel without sharing data. It's important to note that if you log in to the production app and it automatically logs you into the UAT app, there is a possibility of missing the identify call for the UAT app. This can prevent the profile from being properly identified in the UAT environment. Make sure that both apps do not share login information and that the identify call is made correctly in each app to ensure accurate profile creation.

If, despite following these steps, the profile is still not being identified, I recommend checking for suppressed identifiers. As suppressed identifiers [may prevent the proper identification of the profile](https://github.com/customerio/customerio-android/issues/226#issuecomment-1604838642). Please note that in response to your request, we have created a feature request to provide logs when a suppressed identifier is identified 

If you have any further queries or need additional assistance, please don't hesitate to reach out to us.

**Comment by levibostian** [comment] 2023-06-26 16:45
Closing issue because original problem has been resolved. 

Even though the issue is closed, feel free to continue this conversation, @Sanjeev193016.

**Closed by levibostian** 2023-06-26 16:45 UTC
