### ISSUE TITLE
Native support for tracking lifecycle events.

### ISSUE THREAD

**Issue by DimiVlachos** [customerio/customerio-android#301] opened 2024-04-15 21:48 UTC
Enhance Customer.io by adding support for tracking key Android lifecycle events such as 'application installed', 'application opened', 'application backgrounded' etc. This feature would allow for automatic capture of crucial user interaction data, enabling more precise user engagement strategies and reducing reliance on external analytics tools. It would greatly benefit Android developers by integrating essential mobile app metrics directly within the Customer.io platform. I look forward to community and developer feedback to refine and implement this valuable enhancement.

**Comment by mrehan27** [comment] 2024-04-16 08:33
Hey @DimiVlachos, thank you for reaching out and sharing your feedback. I'm happy to share that this feature is planned in our roadmap for this year and should be live in the upcoming months. While I can't share specific timeline at the moment, I can confirm that it's something we have planned.

I'm closing this issue since we already have internal tickets to track the feature, but I'll link this issue to the internal ticket so we can keep you informed about any future progress.

Even though the issue is closed, please don't hesitate to ask any further questions or share more feedback. Your input is important for us to improve our product. Thank you for sharing, and have a great day.

**Closed by mrehan27** 2024-04-16 08:33 UTC
Labels: Usability, Support Escalation
