### ISSUE TITLE
Crash inapp message 

### ISSUE THREAD

**Issue by arseneHuot** [customerio/customerio-android#245] opened 2023-08-20 12:37 UTC
**SDK version:** 3.6.3

**Environment:**Production

**Are logs available?** 
Fatal Exception: java.util.ConcurrentModificationException:
       at java.util.ArrayList$Itr.next(ArrayList.java:860)
       at io.customer.messaginginapp.gist.presentation.GistSdk.handleGistError$messaginginapp_release(GistSdk.kt:228)
       at io.customer.messaginginapp.gist.presentation.GistView.error(GistView.kt:138)
       at io.customer.messaginginapp.gist.presentation.engine.EngineWebView$setupTimeout$1.run(EngineWebView.kt:98)
       at java.util.TimerThread.mainLoop(Timer.java:562)
       at java.util.TimerThread.run(Timer.java:512)

**Describe the bug**
Crash but user without any inapp message (not deployed on our automations)

**To Reproduce**
no idea

**Expected behavior**
no cash

**Comment by mrehan27** [comment] 2023-08-21 14:01
Thank you for reaching out and sharing the details. We apologize for the inconvenience caused by the crash. Based on the stack-trace you've provided, we're actively working on a fix. You can expect this issue to be resolved in an upcoming release. We appreciate your patience and cooperation.

**Comment by arseneHuot** [comment] 2023-08-23 08:23
Great ! 
No problem that was only crashing for few users but we like inapp messages so we prefer to keep it and have 0 crash :)

**Closed** 2023-08-23 09:27 UTC

**Comment by mrehan27** [comment] 2023-08-23 14:33
Thank you for your understanding and continued support! I'm excited to inform you that the issue has been fixed in version `3.6.5`. Please don't hesitate to reach out if there's anything else we can assist you with.
